### ISSUE TITLE
Publish the crate?

### ISSUE THREAD

**Issue by TheKnarf** [TotalKrill/bevy_mod_fornjot#1]
```
$ cargo add bevy_mod_fornjot
    Updating crates.io index
error: the crate `bevy_mod_fornjot` could not be found in registry index.
```

I was able to add it manually by including the following line in my `Cargo.toml`:

```
bevy_mod_fornjot = { git = "https://github.com/TotalKrill/bevy_mod_fornjot" }
```

It would however be nice to actually have it on crates.io.

**Comment by TotalKrill** [comment]
Yeah, I am not really planning on maintaining or releasing this for now. If you would look at the code, the only thing it provides is one function to create a bevy mesh from the output from fornjot. 

Im currently not using this ( altough I might at a future date depending on features implemented in fornjot), so if you want to use this, just copy the function in lib.rs into your own project.
